databases:
  - name: evershop-db
    plan: free
    postgresMajorVersion: 15

services:
  # EverShop Node.js Backend
  - type: web
    name: evershop-app
    plan: free
    runtime: node
    # Build command: Install dependencies and compile the TypeScript source
    buildCommand: "npm install && npm run compile"
    # Start command: Run the production server
    startCommand: "npm run start"
    envVars:
      # Let Render inject the database connection string
      - key: DATABASE_URL
        fromDatabase:
          name: evershop-db
          property: connectionString
      - key: NODE_ENV
        value: production
